### ISSUE TITLE
Jupyter  has been Deprecated

### ISSUE THREAD

**Issue by rectcircle** [DonJayamanne/python-extension-pack#14]
[see here](https://marketplace.visualstudio.com/items?itemName=donjayamanne.jupyter)
![image](https://user-images.githubusercontent.com/18106246/53311727-fbd52d00-38ec-11e9-9155-4995596d908f.png)

**Comment by angelhdz** [comment]
LOOOL i opened an issue with this same name, but now I noticed I opened it in the wrong extension's respository (ms-python.python).

I'm getting this annoying warning every time I open my Python workspace. Tried to uninstall Jupyter or disabling it but it complained that there was an extension depending on it.

Now I know it's the **Python Extension Pack** extension. 

I don't even know if I need Jupyter? Never used it, and I don't know if Python really needs it?

**Comment by agalazis** [comment]
we can close this when #13  gets released

**Comment by osya** [comment]
This issue can be closed. Currently I can successfully delete `Jupyter` extension
