### ISSUE TITLE
MagicPython when code block closed enter issue

### ISSUE THREAD

**Issue by jbwyatt4** [DonJayamanne/python-extension-pack#19]
Issue Type: <b>Bug</b>

Either MagicPython or Code itself. If you click the down arrow for a code block and minimize the code block to one line, then press enter, the newline is added to the second line of the code block then behind the code block. It is a real issue if your code block is at the end of a file.

Steps to Reproduce:
1) Minimize a code block in python by clicking the arrow to the left at the end of the file
2) Move mouse cursor to the end of file which is also the end of the closed code block, say:  class User(Resource):...
3) Press enter

New line is added to the second line of the code block instead of past the code block. I believe it should add a new line after the code block.

Extension version: 1.6.0
VS Code version: Code 1.42.0 (ae08d5460b5a45169385ff3fd44208f431992451, 2020-02-06T10:51:23.649Z)
OS version: Linux x64 5.4.17-200.fc31.x86_64 snap

**Comment by samgermain** [comment]
Written on the Extension Page

> Attention VSCode users: MagicPython is used as the default Python highlighter in Visual Studio Code. Don't install it unless you want or need the cutting edge version of it. You will likely see no difference because you're already using MagicPython.

**Comment by DonJayamanne** [comment]
Closing this issue as this extension pack doesn't add any functionally
