### ISSUE TITLE
p

### ISSUE THREAD

**Issue by ptoru001** [DonJayamanne/python-extension-pack#23]
Issue Type: <b>Bug</b>

Extension activation failed, run the 'Developer: Toggle Developer Tools' command for more information.

nothing on vscode is working

Extension version: 1.6.0
VS Code version: Code 1.54.0 (42e27fe5cdc58539dad9867970326a297eb8cacf, 2021-03-03T02:17:59.499Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv|--crash-reporter-id 8df700d7-f692-4a2d-b9b0-1d5510f8ddfd|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
pythonvspyt602cf:30265443
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30256638
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubsetcf:30265999
pythontbcf:30265426
vspre833:30267464

```

</details>

**Comment by DonJayamanne** [comment]
Please test again, issues was resolved by vscode (it was a problem in vscode, they have since released a new version)
