### ISSUE TITLE
Conflicting commands in `vscode-python` & `vscodeJupyter`

### ISSUE THREAD

**Issue by osya** [DonJayamanne/python-extension-pack#3]
Conflicting commands which exists in both [vscode-python](github.com/Microsoft/vscode-python) & [vscodeJupyter](github.com/DonJayamanne/vscodeJupyter) extensions: `runSelectionLine`, `execCurrentCell`, `execCurrentCellAndAdvance`, `gotToPreviousCell`, `gotToNextCell`

**Comment by DonJayamanne** [comment]
Will be resolved in python extension. This repo merely bundles other extensions.
