### ISSUE TITLE
Ctrl + A + K + F not working due to installed Python extension packs

### ISSUE THREAD

**Issue by luck1004** [DonJayamanne/python-extension-pack#31]
VS Code not working due to installed Python extension pack Ctrl + A + K + F

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, Please report the issue on the faulty extension.
Extension packs merely ship other extensions and thus offer no other functionality, if something is broken then its caused by one of the other extensions included in teh pack

**Comment by luck1004** [comment]
Thank you very much for telling me. I checked if it was because of another
program I use, but there was no problem, and Ctrl+A+K+F is not possible
because I only used and ran the extension. One of the Python expansion pack
programs seems to be the problem.

2023년 2월 3일 (금) 오전 4:36, Don Jayamanne ***@***.***>님이 작성:

**Comment by luck1004** [comment]
Thank you so much! :)
